//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK_sales_management.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.leads = new HashSet<lead>();
        }
    
        public int emp_number { get; set; }
        public string emp_firstname { get; set; }
        public string emp_middlename { get; set; }
        public string emp_lastname { get; set; }
        public string emp_username { get; set; }
        public string emp_password { get; set; }
        public string phone_number { get; set; }
        public int user_type_number { get; set; }
        public int branch_number { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual users_types users_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lead> leads { get; set; }
    }
}
