//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK_sales_management.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class installation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public installation()
        {
            this.tasks_installation = new HashSet<tasks_installation>();
            this.rates = new HashSet<rate>();
        }
    
        public int installation_number { get; set; }
        public string installation_name { get; set; }
        public string estimated_by { get; set; }
        public System.DateTime statrt_date { get; set; }
        public double mileages_to_destination { get; set; }
        public int required_hotel_nights { get; set; }
        public double mileages_from_hotel { get; set; }
        public double installation_days { get; set; }
        public Nullable<double> total_per_diem_cost { get; set; }
        public Nullable<double> total_installation_labor_cost { get; set; }
        public Nullable<double> total_operational_expenses { get; set; }
        public Nullable<double> total_construction_materials_cost { get; set; }
        public Nullable<double> total_tile_cost { get; set; }
        public Nullable<double> total_travel_cost { get; set; }
        public int lead_number { get; set; }
    
        public virtual lead lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasks_installation> tasks_installation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate> rates { get; set; }
    }
}
