//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK_sales_management.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int task_number { get; set; }
        public bool special_task { get; set; }
        public string task_name { get; set; }
        public string task_main_cat { get; set; }
        public string task_sub_cat { get; set; }
    
        public virtual tasks_installation tasks_installation { get; set; }
    }
}
